import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Rscue</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-5xl font-bold text-white sm:text-[5rem]">Rscue</h1>
        <AnimalEntries />

        <div className="flex flex-col items-center gap-2">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <AuthShowcase />
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

interface AnimalEntriesProps {}
const AnimalEntries: React.FC<AnimalEntriesProps> = () => {
  const { data: animals, isLoading } = api.animal.getAll.useQuery();
  if (isLoading) return <div>Fetching animals...</div>;
  return (
    <div className="text-white">
      <h2 className="text-2xl font-bold">Animals</h2>
      {animals?.map((animal) => (
        <div key={animal.type + "-" + animal.name}>
          <p>Name: {animal.name}</p>
          <p>Type: {animal.type}</p>
          <p>Description: {animal.description}</p>
        </div>
      ))}
    </div>
  );
};
